const strings = {
  es: {
    loginTitle: 'Iniciar Sesión',
    username: 'Nombre de usuario',
    password: 'Contraseña',
    login: 'Ingresar',
    register: 'Registrarse',
    registerTitle: 'Registrarse',
    name: 'Nombre',
    surname: 'Apellido',
    email: 'Email',
    birthdate: 'Fecha de nacimiento',
    uploadAvatar: 'Subir Avatar',
    dashboardTitle: 'Penca Mundial 2026',
    playerDashboardTitle: 'Hola, {{name}}',
    playerDashboardHint: 'Cargá tus pronósticos y revisá el ranking.',
    predictionProgress: 'Pronósticos abiertos: {{predicted}}/{{total}} cargados',
    approvalPendingTitle: 'Solicitud pendiente',
    approvalPendingBody: 'Tu usuario ya fue creado. Para ser aprobado y empezar a jugar, contactá con el administrador.',
    approvalRejectedTitle: 'Solicitud no aprobada',
    approvalRejectedBody: 'Tu acceso no está activo. Contactá con el administrador si creés que fue un error.',
    sharePenca: 'Compartir penca',
    shareText: 'Sumate a la Penca Mundial 2026: {{url}}. Después de registrarte, contactá con el administrador para que apruebe tu usuario.',
    shareCopied: 'Invitación lista para compartir',
    shareCopyError: 'No pudimos copiar la invitación',
    playerPageHint: 'Partidos y ranking',
    noPencas: 'No pudimos cargar la penca.',
    hide: 'Ocultar',
    competition: 'Competencia',
    networkError: 'Error de red',
    loading: 'Cargando...',
    logout: 'Cerrar Sesión',
    editProfile: 'Editar Perfil',
    myProfile: 'Mi Perfil',
    predictions: 'Predicciones',
    knockout: 'Eliminatorias',
    save: 'Guardar',
    delete: 'Eliminar',
    matches: 'Partidos',
    pencaTabMatches: 'Partidos',
    pencaTabRanking: 'Ranking',
    pencaTabInfo: 'Información',
    pencaTabsLabel: 'Secciones de la penca',
    scheduleTbd: 'Horario a definir',
    dateToBeDefined: 'Fecha a definir',
    otherMatches: 'Otros partidos',
    importCompetition: 'Importar competencia',
    downloadExampleJson: 'Descargar ejemplo JSON',
    downloadWorldCupJson: 'Descargar Mundial 2026',
    downloadGuideDoc: 'Descargar guía JSON',
    addMatch: 'Agregar partido',
    team1Label: 'Equipo 1',
    team2Label: 'Equipo 2',
    dateLabel: 'Fecha',
    timeLabel: 'Hora',
    seriesLabel: 'Serie',
    kickoffLabel: 'Inicio (fecha y hora)',
    localKickoffLabel: 'Horario local',
    originalDateLabel: 'Fecha original',
    originalTimeLabel: 'Hora original',
    originalTimezoneLabel: 'Zona horaria original',
    venueCountryLabel: 'País',
    venueCityLabel: 'Ciudad',
    venueStadiumLabel: 'Estadio',
    scoreTeam1Label: 'Goles equipo 1',
    scoreTeam2Label: 'Goles equipo 2',
    importCompetitionHint: 'Seleccioná un archivo JSON con la competencia. El formato está detallado en la guía descargable.',
    selectJsonFile: 'Seleccionar archivo JSON',
    matchesCountLabel: 'Partidos: {{count}}',
    groupsCountLabel: 'Grupos detectados: {{count}}',
    timezonesDetected: 'Zonas horarias detectadas: {{count}}',
    previewMatches: 'Vista previa de partidos',
    confirmImport: 'Importar',
    matchCreated: 'Partido creado',
    teamNamesRequired: 'Debes ingresar ambos equipos',
    ranking: 'Ranking',
    participant: 'Participante',
    score: 'Puntaje',
    rules: 'Reglas',
    prizes: 'Premios',
    noRules: 'Sin reglas definidas',
    noPrizes: 'Sin premios definidos',
    close: 'Cerrar',
    public: 'Pública',
    exact: 'Exacto',
    outcome: 'Ganador',
    goals: 'Goles',
    scoring: 'Sistema de puntos',
    regulation: 'Reglamento',
    awards: 'Premios',
    requests: 'Solicitudes',
    participants: 'Participantes',
    back: 'Atrás',
    next: 'Siguiente',
    create: 'Crear',
    newCompetition: 'Nueva Competencia',
    bracketPrototype: 'Prototipo de Llave',
    vs: 'vs',
    adminTitle: 'Administración',
    adminTabOverview: 'Resumen',
    adminTabCompetitions: 'Competencias',
    adminTabMatches: 'Partidos',
    adminTabPencas: 'Penca',
    adminTabSettings: 'Configuración',
    adminOverviewTitle: 'Estado general',
    adminStatsCompetitions: 'Competencias',
    adminStatsMatches: 'Partidos',
    adminStatsPencas: 'Penca',
    adminStatsPlayers: 'Jugadores',
    adminStatsUpdated: 'Actualizado',
    auditSettingsTitle: 'Auditoría',
    auditDisabled: 'La auditoría está desactivada para evitar sobrecarga en la base de datos.',
    auditEnabled: 'La auditoría está habilitada. Elegí qué eventos querés registrar.',
    auditEnable: 'Habilitar auditoría',
    auditDisable: 'Desactivar auditoría',
    auditTypesLabel: 'Eventos a auditar',
    auditTypeUser: 'Cambios de administradores y jugadores',
    auditTypePenca: 'Cambios en pencas',
    auditTypePrediction: 'Cambios en predicciones',
    auditSaveSuccess: 'Configuración de auditoría guardada',
    auditSaveError: 'No se pudo guardar la configuración de auditoría',
    competitions: 'Competencias',
    pencas: 'Penca',
    adminMatchesFilter: 'Filtrar partidos',
    adminMatchesSearch: 'Buscar por equipo, sede o grupo',
    adminMatchesStatus: 'Estado',
    adminMatchesGrouped: 'Grupos detectados',
    adminMatchesRefresh: 'Refrescar lista',
    adminMatchesSearchPlaceholder: 'Equipo, grupo, estadio o ciudad',
    adminMatchesDateFilter: 'Fecha',
    adminMatchesGroupFilter: 'Grupo',
    adminMatchesFiltered: '{{count}} partidos visibles',
    adminMatchesClearFilters: 'Limpiar filtros',
    adminMatchesNoFilteredResults: 'No hay partidos que coincidan con esos filtros.',
    adminMatchesNoResults: 'No hay partidos cargados.',
    adminClearMatches: 'Borrar todos los partidos',
    adminClearMatchesConfirm: '¿Seguro que querés borrar todos los partidos y predicciones cargadas? Esta acción no se puede deshacer.',
    adminClearMatchesSuccess: 'Se borraron {{count}} partidos.',
    adminResetFixture: 'Reiniciar con fixture oficial',
    adminResetFixturePrompt: 'Esto borra partidos, resultados y predicciones, y vuelve a cargar el fixture oficial. Escribí REINICIAR para confirmar.',
    adminResetFixtureCancelled: 'Reinicio cancelado: tenés que escribir REINICIAR.',
    adminResetFixtureSuccess: 'Fixture reiniciado. Se importaron {{count}} partidos.',
    adminMatchesNoCompetition: 'Sin competencia seleccionada',
    adminMatchesTotal: '{{count}} partidos',
    adminMatchesLoaded: '{{count}} con resultado',
    adminMatchesPending: '{{count}} pendientes',
    adminResultsTitle: 'Carga de resultados',
    adminResultsHelp: 'Ingresá los marcadores reales y guardá. Al guardar o recalcular, las eliminatorias se actualizan con los cruces que ya tengan etapa anterior definida.',
    adminResultSaved: 'Resultado guardado',
    adminBracketRecalculated: 'Eliminatorias recalculadas',
    adminMatchLoaded: 'Cargado',
    adminMatchPending: 'Pendiente',
    adminSaveResult: 'Guardar resultado',
    adminApprovalsTitle: 'Aprobación de jugadores',
    adminApprovalsHelp: 'Solo los usuarios aprobados pueden cargar pronósticos y aparecer en el ranking.',
    adminNoPendingUsers: 'No hay jugadores pendientes de aprobación.',
    adminApprovedUsers: '{{count}} aprobados',
    adminUserApproved: 'Jugador aprobado. {{emailStatus}}',
    adminUserRejected: 'Jugador rechazado',
    emailSent: 'Email enviado',
    emailNotConfigured: 'Email no configurado',
    adminMissingTitle: 'Faltantes y recordatorios',
    adminMissingHelp: 'Controlá quiénes tienen pronósticos pendientes, qué partidos cierran pronto y qué resultados faltan cargar.',
    adminSendReminders: 'Enviar recordatorios',
    adminMissingPlayers: '{{count}} jugadores con faltantes',
    adminClosingSoon: '{{count}} partidos cierran pronto',
    adminWithoutResult: '{{count}} sin resultado',
    adminPlayerMissingLine: '{{missing}} de {{total}} pronósticos abiertos pendientes',
    adminRemindersSent: 'Recordatorios enviados: {{sent}}/{{total}}',
    otherMatches: 'Otros partidos',
    generateBracket: 'Generar/Actualizar eliminatorias',
    saveOrder: 'Guardar orden',
    saveRound: 'Guardar ronda',
    recalculateBracket: 'Recalcular eliminatorias',
    groups: 'Grupos',
    groupsEmpty: 'La tabla de grupos aparecerá cuando haya partidos cargados.',
    integrants: 'Integrantes',
    qualifiers: 'Clasificados',
    fixtureFile: 'Archivo JSON',
    loadFixture: 'Cargar fixture',
    invalidJsonFile: 'Archivo JSON inválido',
    group: 'Grupo',
    team: 'Equipo',
    pts: 'Pts',
    playedShort: 'PJ',
    w: 'W',
    d: 'D',
    l: 'L',
    gd: 'DG',
    gf: 'GF',
    result: 'Resultado',
    pointsEarned: 'Puntos',
    difference: 'Diferencia',
    searchPlayer: 'Buscar jugador',
    searchPlayerPlaceholder: 'Ingresá un nombre de usuario',
    noRankingResults: 'No encontramos jugadores con ese nombre.',
    pointsBreakdownTitle: 'Detalle de puntos en {{stage}}',
    pointsBreakdownDefaultStage: 'esta etapa',
    pointsBreakdownHint: 'No se asignaron puntos adicionales en esta etapa.',
    pointsBreakdownExact: 'Marcador exacto',
    pointsBreakdownOutcome: 'Resultado correcto',
    pointsBreakdownGoalDifference: 'Diferencia de goles acertada',
    pointsBreakdownTeamGoals: 'Goles exactos de {{team}}',
    pointsBreakdownPenaltyWinner: 'Ganador por penales',
    viewPointsDetails: 'Ver detalle de puntos',
    hidePointsDetails: 'Ocultar detalle de puntos',
    penaltyWinnerLabel: 'Ganador por penales',
    penaltyWinnerResult: 'Ganador por penales: {{team}}',
    saveToCalendar: 'Guardar en calendario',
    predictionClosed: 'El pronóstico está cerrado para este partido.',
    allMatches: 'Todos',
    today: 'Hoy',
    tomorrow: 'Mañana',
    upcoming: 'Próximos',
    played: 'Jugados',
    jumpToDate: 'Ir a fecha',
    jumpToDatePlaceholder: 'Elegir fecha',
    jumpToStage: 'Ir a etapa',
    jumpToStagePlaceholder: 'Elegir etapa',
    viewRules: 'Ver reglas',
    format: 'Formato',
    participantsShort: 'jugadores',
    mode_group_stage_knockout: 'Grupos + Eliminación',
    mode_league: 'Liga',
    mode_knockout: 'Eliminación directa',
    mode_custom: 'Formato personalizado',
    goalDifferenceLabel: 'Diferencia de goles',
    teamGoalsLabel: 'Goles por equipo',
    cleanSheetLabel: 'Arco en cero',
    ruleExact: 'puntos por acertar el marcador exacto',
    ruleOutcome: 'puntos por acertar el resultado (victoria/empate)',
    ruleGoalDifference: 'puntos por acertar la diferencia de goles',
    ruleTeamGoals: 'punto por cada equipo con goles exactos',
    ruleCleanSheet: 'punto extra por cada arco en cero pronosticado',
    approve: 'Aprobar',
    remove: 'Eliminar',
    noRequests: 'No hay solicitudes pendientes',
    noParticipants: 'Sin participantes',
    noRanking: 'Sin puntajes registrados',
    adminCleanupTitle: 'Limpieza de datos',
    adminCleanupDescription: 'Elegí qué colecciones querés limpiar para quitar datos antiguos o de prueba.',
    adminCleanupWarning: 'Esta acción no se puede deshacer. Hacé un backup antes de continuar.',
    adminCleanupSelectAll: 'Seleccionar todo',
    adminCleanupAction: 'Limpiar seleccionadas',
    adminCleanupConfirmTitle: 'Confirmar limpieza',
    adminCleanupConfirmMessage: '¿Seguro que querés eliminar los datos seleccionados? Esta acción es irreversible.',
    adminCleanupSuccess: 'Limpieza realizada con éxito',
    adminCleanupEmpty: 'Seleccioná al menos una colección',
    adminCleanupUsersNote: 'Los administradores se conservan automáticamente.',
    adminCollections: 'Colecciones',
    adminSelected: 'Seleccionadas',
    pencaLookupHint: 'Consultá el estado general de la penca.',
    pencaLookupButton: 'Consultar penca',
    pencaLookupPlayers: 'Jugadores habilitados'
  },
  en: {
    loginTitle: 'Login',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    register: 'Register',
    registerTitle: 'Register',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    birthdate: 'Birthdate',
    uploadAvatar: 'Upload Avatar',
    dashboardTitle: 'World Cup 2026 Pool',
    playerDashboardTitle: 'Hi, {{name}}',
    playerDashboardHint: 'Enter your predictions and check the ranking.',
    predictionProgress: 'Open predictions: {{predicted}}/{{total}} saved',
    approvalPendingTitle: 'Request pending',
    approvalPendingBody: 'Your user was created. To be approved and start playing, contact the administrator.',
    approvalRejectedTitle: 'Request not approved',
    approvalRejectedBody: 'Your access is not active. Contact the administrator if you think this was a mistake.',
    sharePenca: 'Share pool',
    shareText: 'Join the World Cup 2026 Pool: {{url}}. After registering, contact the administrator to approve your user.',
    shareCopied: 'Invitation ready to share',
    shareCopyError: 'We could not copy the invitation',
    playerPageHint: 'Matches and ranking',
    noPencas: 'We could not load the pool.',
    hide: 'Hide',
    competition: 'Competition',
    networkError: 'Network error',
    loading: 'Loading...',
    logout: 'Logout',
    editProfile: 'Edit Profile',
    myProfile: 'My Profile',
    predictions: 'Predictions',
    knockout: 'Knockout',
    save: 'Save',
    delete: 'Delete',
    matches: 'Matches',
    pencaTabMatches: 'Matches',
    pencaTabRanking: 'Ranking',
    pencaTabInfo: 'Info',
    pencaTabsLabel: 'Penca sections',
    scheduleTbd: 'Schedule to be confirmed',
    dateToBeDefined: 'Date to be confirmed',
    otherMatches: 'Other matches',
    importCompetition: 'Import competition',
    downloadExampleJson: 'Download sample JSON',
    downloadWorldCupJson: 'Download World Cup 2026',
    downloadGuideDoc: 'Download JSON guide',
    addMatch: 'Add match',
    team1Label: 'Team 1',
    team2Label: 'Team 2',
    dateLabel: 'Date',
    timeLabel: 'Time',
    seriesLabel: 'Stage',
    kickoffLabel: 'Kickoff (date & time)',
    localKickoffLabel: 'Local time',
    originalDateLabel: 'Original date',
    originalTimeLabel: 'Original time',
    originalTimezoneLabel: 'Original timezone',
    venueCountryLabel: 'Country',
    venueCityLabel: 'City',
    venueStadiumLabel: 'Stadium',
    scoreTeam1Label: 'Team 1 goals',
    scoreTeam2Label: 'Team 2 goals',
    importCompetitionHint: 'Select a JSON file with the competition definition. The format is described in the downloadable guide.',
    selectJsonFile: 'Choose JSON file',
    matchesCountLabel: 'Matches: {{count}}',
    groupsCountLabel: 'Groups detected: {{count}}',
    timezonesDetected: 'Time zones detected: {{count}}',
    previewMatches: 'Match preview',
    confirmImport: 'Import',
    matchCreated: 'Match created',
    teamNamesRequired: 'Both teams are required',
    ranking: 'Ranking',
    participant: 'Participant',
    score: 'Score',
    rules: 'Rules',
    prizes: 'Prizes',
    noRules: 'No rules defined',
    noPrizes: 'No prizes defined',
    close: 'Close',
    public: 'Public',
    exact: 'Exact',
    outcome: 'Winner',
    goals: 'Goals',
    scoring: 'Scoring',
    regulation: 'Rules',
    awards: 'Prizes',
    requests: 'Requests',
    participants: 'Participants',
    back: 'Back',
    next: 'Next',
    create: 'Create',
    newCompetition: 'New Competition',
    bracketPrototype: 'Bracket Prototype',
    vs: 'vs',
    adminTitle: 'Administration',
    adminTabOverview: 'Overview',
    adminTabCompetitions: 'Competitions',
    adminTabMatches: 'Matches',
    adminTabPencas: 'Pool',
    adminTabSettings: 'Settings',
    adminOverviewTitle: 'System status',
    adminStatsCompetitions: 'Competitions',
    adminStatsMatches: 'Matches',
    adminStatsPencas: 'Pool',
    adminStatsPlayers: 'Players',
    adminStatsUpdated: 'Updated',
    auditSettingsTitle: 'Audit log',
    auditDisabled: 'Audit logging is disabled to reduce database load.',
    auditEnabled: 'Audit logging is enabled. Choose which events to record.',
    auditEnable: 'Enable audit',
    auditDisable: 'Disable audit',
    auditTypesLabel: 'Events to audit',
    auditTypeUser: 'Admin and player changes',
    auditTypePenca: 'Pool changes',
    auditTypePrediction: 'Prediction changes',
    auditSaveSuccess: 'Audit settings saved',
    auditSaveError: 'Could not save audit settings',
    competitions: 'Competitions',
    pencas: 'Pools',
    adminMatchesFilter: 'Filter matches',
    adminMatchesSearch: 'Search by team, venue or group',
    adminMatchesStatus: 'Status',
    adminMatchesGrouped: 'Detected groups',
    adminMatchesRefresh: 'Refresh list',
    adminMatchesSearchPlaceholder: 'Team, group, stadium or city',
    adminMatchesDateFilter: 'Date',
    adminMatchesGroupFilter: 'Group',
    adminMatchesFiltered: '{{count}} visible matches',
    adminMatchesClearFilters: 'Clear filters',
    adminMatchesNoFilteredResults: 'No matches match those filters.',
    adminMatchesNoResults: 'No matches available.',
    adminClearMatches: 'Delete all matches',
    adminClearMatchesConfirm: 'Are you sure you want to delete every match and saved prediction? This cannot be undone.',
    adminClearMatchesSuccess: '{{count}} matches deleted.',
    adminResetFixture: 'Reset official fixture',
    adminResetFixturePrompt: 'This deletes matches, results, and predictions, then imports the official fixture again. Type REINICIAR to confirm.',
    adminResetFixtureCancelled: 'Reset cancelled: you must type REINICIAR.',
    adminResetFixtureSuccess: 'Fixture reset. {{count}} matches imported.',
    adminMatchesNoCompetition: 'No competition selected',
    adminMatchesTotal: '{{count}} matches',
    adminMatchesLoaded: '{{count}} with results',
    adminMatchesPending: '{{count}} pending',
    adminResultsTitle: 'Results entry',
    adminResultsHelp: 'Enter the real scores and save. Saving or recalculating updates knockout matchups whenever the previous stage is resolved.',
    adminResultSaved: 'Result saved',
    adminBracketRecalculated: 'Knockout bracket recalculated',
    adminMatchLoaded: 'Loaded',
    adminMatchPending: 'Pending',
    adminSaveResult: 'Save result',
    adminApprovalsTitle: 'Player approvals',
    adminApprovalsHelp: 'Only approved users can enter predictions and appear in the ranking.',
    adminNoPendingUsers: 'No players are pending approval.',
    adminApprovedUsers: '{{count}} approved',
    adminUserApproved: 'Player approved. {{emailStatus}}',
    adminUserRejected: 'Player rejected',
    emailSent: 'Email sent',
    emailNotConfigured: 'Email not configured',
    adminMissingTitle: 'Missing items and reminders',
    adminMissingHelp: 'Track players with pending predictions, matches closing soon, and results still missing.',
    adminSendReminders: 'Send reminders',
    adminMissingPlayers: '{{count}} players missing picks',
    adminClosingSoon: '{{count}} matches closing soon',
    adminWithoutResult: '{{count}} without result',
    adminPlayerMissingLine: '{{missing}} of {{total}} open predictions pending',
    adminRemindersSent: 'Reminders sent: {{sent}}/{{total}}',
    otherMatches: 'Other matches',
    generateBracket: 'Generate/Update knockout',
    saveOrder: 'Save order',
    saveRound: 'Save round',
    recalculateBracket: 'Recalculate bracket',
    groups: 'Groups',
    groupsEmpty: 'Group tables will appear once matches are loaded.',
    integrants: 'Teams',
    qualifiers: 'Qualifiers',
    fixtureFile: 'JSON File',
    loadFixture: 'Load fixture',
    invalidJsonFile: 'Invalid JSON file',
    group: 'Group',
    team: 'Team',
    pts: 'Pts',
    playedShort: 'P',
    w: 'W',
    d: 'D',
    l: 'L',
    gd: 'GD',
    gf: 'GF',
    result: 'Result',
    pointsEarned: 'Points',
    difference: 'Difference',
    searchPlayer: 'Search player',
    searchPlayerPlaceholder: 'Type a username',
    noRankingResults: 'No players match that name.',
    pointsBreakdownTitle: 'Points detail in {{stage}}',
    pointsBreakdownDefaultStage: 'this stage',
    pointsBreakdownHint: 'No additional bonuses were awarded in this stage.',
    pointsBreakdownExact: 'Exact score',
    pointsBreakdownOutcome: 'Correct outcome',
    pointsBreakdownGoalDifference: 'Goal difference matched',
    pointsBreakdownTeamGoals: '{{team}} exact goals',
    pointsBreakdownPenaltyWinner: 'Penalty shootout winner',
    viewPointsDetails: 'View points details',
    hidePointsDetails: 'Hide points details',
    penaltyWinnerLabel: 'Penalty winner',
    penaltyWinnerResult: 'Penalty winner: {{team}}',
    saveToCalendar: 'Save to calendar',
    predictionClosed: 'Predictions are closed for this match.',
    allMatches: 'All',
    today: 'Today',
    tomorrow: 'Tomorrow',
    upcoming: 'Upcoming',
    played: 'Played',
    jumpToDate: 'Jump to date',
    jumpToDatePlaceholder: 'Select a date',
    jumpToStage: 'Jump to stage',
    jumpToStagePlaceholder: 'Select a stage',
    viewRules: 'View rules',
    format: 'Format',
    participantsShort: 'players',
    mode_group_stage_knockout: 'Group + Knockout',
    mode_league: 'League',
    mode_knockout: 'Single elimination',
    mode_custom: 'Custom format',
    goalDifferenceLabel: 'Goal difference',
    teamGoalsLabel: 'Team goals',
    cleanSheetLabel: 'Clean sheet bonus',
    ruleExact: 'points for the exact scoreline',
    ruleOutcome: 'points for the correct outcome (win/draw)',
    ruleGoalDifference: 'points for the correct goal difference',
    ruleTeamGoals: 'point for each team with the exact goals',
    ruleCleanSheet: 'extra point for correctly predicting a clean sheet',
    approve: 'Approve',
    remove: 'Remove',
    noRequests: 'No pending requests',
    noParticipants: 'No participants yet',
    noRanking: 'No scores recorded',
    adminCleanupTitle: 'Data cleanup',
    adminCleanupDescription: 'Choose which collections to clear to remove outdated or testing data.',
    adminCleanupWarning: 'This action cannot be undone. Make a backup before continuing.',
    adminCleanupSelectAll: 'Select all',
    adminCleanupAction: 'Clean selected',
    adminCleanupConfirmTitle: 'Confirm cleanup',
    adminCleanupConfirmMessage: 'Are you sure you want to delete the selected data? This cannot be undone.',
    adminCleanupSuccess: 'Cleanup completed successfully',
    adminCleanupEmpty: 'Select at least one collection',
    adminCleanupUsersNote: 'Administrators are preserved automatically.',
    adminCollections: 'Collections',
    adminSelected: 'Selected',
    pencaLookupHint: 'Enter the code to view pool details before joining.',
    pencaLookupButton: 'Check pool',
    pencaLookupPlayers: 'Approved players'
  }
};

export default strings;
