const strings = {
  es: {
    loginTitle: 'Iniciar Sesión',
    username: 'Nombre de usuario',
    password: 'Contraseña',
    login: 'Ingresar',
    register: 'Registrarse',
    registerTitle: 'Registrarse',
    name: 'Nombre',
    surname: 'Apellido',
    email: 'Email',
    birthdate: 'Fecha de nacimiento',
    uploadAvatar: 'Subir Avatar',
    dashboardTitle: 'Mis Pencas',
    noPencas: 'No estás en ninguna penca.',
    joinAnother: 'Unirse a otra penca',
    hide: 'Ocultar',
    join: 'Unirse',
    code: 'Código',
    competition: 'Competencia',
    requestSent: 'Solicitud enviada',
    networkError: 'Error de red',
    logout: 'Cerrar Sesión',
    editProfile: 'Editar Perfil',
    myProfile: 'Mi Perfil',
    predictions: 'Predicciones',
    knockout: 'Eliminatorias',
    save: 'Guardar',
    matches: 'Partidos',
    scheduleTbd: 'Horario a definir',
    addMatch: 'Agregar partido',
    team1Label: 'Equipo 1',
    team2Label: 'Equipo 2',
    dateLabel: 'Fecha',
    timeLabel: 'Hora',
    seriesLabel: 'Serie',
    matchCreated: 'Partido creado',
    teamNamesRequired: 'Debes ingresar ambos equipos',
    ranking: 'Ranking',
    participant: 'Participante',
    score: 'Puntaje',
    rules: 'Reglas',
    prizes: 'Premios',
    noRules: 'Sin reglas definidas',
    noPrizes: 'Sin premios definidos',
    close: 'Cerrar',
    public: 'Pública',
    exact: 'Exacto',
    outcome: 'Ganador',
    goals: 'Goles',
    regulation: 'Reglamento',
    awards: 'Premios',
    requests: 'Solicitudes',
    participants: 'Participantes',
    ownerMyPencas: 'Mis Pencas',
    back: 'Atrás',
    next: 'Siguiente',
    create: 'Crear',
    newCompetition: 'Nueva Competencia',
    bracketPrototype: 'Prototipo de Llave',
    vs: 'vs',
    adminTitle: 'Administración',
    competitions: 'Competencias',
    owners: 'Owners',
    pencas: 'Pencas',
    owner: 'Owner',
    generateBracket: 'Generar/Actualizar eliminatorias',
    saveOrder: 'Guardar orden',
    saveRound: 'Guardar ronda',
    updateResults: 'Actualizar resultados',
    groups: 'Grupos',
    integrants: 'Integrantes',
    qualifiers: 'Clasificados',
    fixtureFile: 'Archivo JSON',
    loadFixture: 'Cargar fixture',
    invalidJsonFile: 'Archivo JSON inválido',
    group: 'Grupo',
    team: 'Equipo',
    pts: 'Pts',
    w: 'W',
    d: 'D',
    l: 'L',
    gd: 'DG',
    gf: 'GF',
    result: 'Resultado',
    pointsEarned: 'Puntos',
    difference: 'Diferencia',
    allMatches: 'Todos',
    upcoming: 'Próximos',
    played: 'Jugados',
    viewRules: 'Ver reglas',
    format: 'Formato',
    participantsShort: 'jugadores',
    mode_group_stage_knockout: 'Grupos + Eliminación',
    mode_league: 'Liga',
    mode_knockout: 'Eliminación directa',
    mode_custom: 'Formato personalizado',
    goalDifferenceLabel: 'Diferencia de goles',
    teamGoalsLabel: 'Goles por equipo',
    cleanSheetLabel: 'Arco en cero',
    ruleExact: 'puntos por acertar el marcador exacto',
    ruleOutcome: 'puntos por acertar el resultado (victoria/empate)',
    ruleGoalDifference: 'puntos por acertar la diferencia de goles',
    ruleTeamGoals: 'punto por cada equipo con goles exactos',
    ruleCleanSheet: 'punto extra por cada arco en cero pronosticado',
    approve: 'Aprobar',
    remove: 'Eliminar',
    noRequests: 'No hay solicitudes pendientes',
    noParticipants: 'Sin participantes',
    noRanking: 'Sin puntajes registrados'
  },
  en: {
    loginTitle: 'Login',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    register: 'Register',
    registerTitle: 'Register',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    birthdate: 'Birthdate',
    uploadAvatar: 'Upload Avatar',
    dashboardTitle: 'My Pools',
    noPencas: 'You are not in any pool.',
    joinAnother: 'Join another pool',
    hide: 'Hide',
    join: 'Join',
    code: 'Code',
    competition: 'Competition',
    requestSent: 'Request sent',
    networkError: 'Network error',
    logout: 'Logout',
    editProfile: 'Edit Profile',
    myProfile: 'My Profile',
    predictions: 'Predictions',
    knockout: 'Knockout',
    save: 'Save',
    matches: 'Matches',
    scheduleTbd: 'Schedule to be confirmed',
    addMatch: 'Add match',
    team1Label: 'Team 1',
    team2Label: 'Team 2',
    dateLabel: 'Date',
    timeLabel: 'Time',
    seriesLabel: 'Stage',
    matchCreated: 'Match created',
    teamNamesRequired: 'Both teams are required',
    ranking: 'Ranking',
    participant: 'Participant',
    score: 'Score',
    rules: 'Rules',
    prizes: 'Prizes',
    noRules: 'No rules defined',
    noPrizes: 'No prizes defined',
    close: 'Close',
    public: 'Public',
    exact: 'Exact',
    outcome: 'Winner',
    goals: 'Goals',
    regulation: 'Rules',
    awards: 'Prizes',
    requests: 'Requests',
    participants: 'Participants',
    ownerMyPencas: 'My Pools',
    back: 'Back',
    next: 'Next',
    create: 'Create',
    newCompetition: 'New Competition',
    bracketPrototype: 'Bracket Prototype',
    vs: 'vs',
    adminTitle: 'Administration',
    competitions: 'Competitions',
    owners: 'Owners',
    pencas: 'Pools',
    owner: 'Owner',
    generateBracket: 'Generate/Update knockout',
    saveOrder: 'Save order',
    saveRound: 'Save round',
    updateResults: 'Update results',
    groups: 'Groups',
    integrants: 'Teams',
    qualifiers: 'Qualifiers',
    fixtureFile: 'JSON File',
    loadFixture: 'Load fixture',
    invalidJsonFile: 'Invalid JSON file',
    group: 'Group',
    team: 'Team',
    pts: 'Pts',
    w: 'W',
    d: 'D',
    l: 'L',
    gd: 'GD',
    gf: 'GF',
    result: 'Result',
    pointsEarned: 'Points',
    difference: 'Difference',
    allMatches: 'All',
    upcoming: 'Upcoming',
    played: 'Played',
    viewRules: 'View rules',
    format: 'Format',
    participantsShort: 'players',
    mode_group_stage_knockout: 'Group + Knockout',
    mode_league: 'League',
    mode_knockout: 'Single elimination',
    mode_custom: 'Custom format',
    goalDifferenceLabel: 'Goal difference',
    teamGoalsLabel: 'Team goals',
    cleanSheetLabel: 'Clean sheet bonus',
    ruleExact: 'points for the exact scoreline',
    ruleOutcome: 'points for the correct outcome (win/draw)',
    ruleGoalDifference: 'points for the correct goal difference',
    ruleTeamGoals: 'point for each team with the exact goals',
    ruleCleanSheet: 'extra point for correctly predicting a clean sheet',
    approve: 'Approve',
    remove: 'Remove',
    noRequests: 'No pending requests',
    noParticipants: 'No participants yet',
    noRanking: 'No scores recorded'
  }
};

export default strings;
