const strings = {
  es: {
    loginTitle: 'Iniciar Sesión',
    username: 'Nombre de usuario',
    password: 'Contraseña',
    login: 'Ingresar',
    register: 'Registrarse',
    registerTitle: 'Registrarse',
    name: 'Nombre',
    surname: 'Apellido',
    email: 'Email',
    birthdate: 'Fecha de nacimiento',
    uploadAvatar: 'Subir Avatar',
    dashboardTitle: 'Mis Pencas',
    noPencas: 'No estás en ninguna penca.',
    joinAnother: 'Unirse a otra penca',
    hide: 'Ocultar',
    join: 'Unirse',
    code: 'Código',
    competition: 'Competencia',
    requestSent: 'Solicitud enviada',
    networkError: 'Error de red',
    logout: 'Logout',
    predictions: 'Predicciones',
    knockout: 'Eliminatorias',
    save: 'Guardar',
    matches: 'Partidos',
    ranking: 'Ranking',
    participant: 'Participante',
    score: 'Puntaje',
    rules: 'Reglas',
    prizes: 'Premios',
    noRules: 'Sin reglas definidas',
    noPrizes: 'Sin premios definidos',
    close: 'Cerrar',
    public: 'Pública',
    exact: 'Exacto',
    outcome: 'Ganador',
    goals: 'Goles',
    regulation: 'Reglamento',
    awards: 'Premios',
    requests: 'Solicitudes',
    participants: 'Participantes',
    ownerMyPencas: 'Mis Pencas',
    back: 'Atrás',
    next: 'Siguiente',
    create: 'Crear',
    newCompetition: 'Nueva Competencia',
    bracketPrototype: 'Prototipo de Llave',
    vs: 'vs'
    adminTitle: 'Administración',
    competitions: 'Competencias',
    owners: 'Owners',
    pencas: 'Pencas',
    owner: 'Owner',
    generateBracket: 'Generar/Actualizar eliminatorias',
    saveOrder: 'Guardar orden',
    saveRound: 'Guardar ronda',
    groups: 'Grupos',
    integrants: 'Integrantes',
    qualifiers: 'Clasificados',
    group: 'Grupo',
    team: 'Equipo',
    pts: 'Pts',
    w: 'W',
    d: 'D',
    l: 'L',
    gd: 'DG',
    gf: 'GF'
  },
  en: {
    loginTitle: 'Login',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    register: 'Register',
    registerTitle: 'Register',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    birthdate: 'Birthdate',
    uploadAvatar: 'Upload Avatar',
    dashboardTitle: 'My Pools',
    noPencas: 'You are not in any pool.',
    joinAnother: 'Join another pool',
    hide: 'Hide',
    join: 'Join',
    code: 'Code',
    competition: 'Competition',
    requestSent: 'Request sent',
    networkError: 'Network error',
    logout: 'Logout',
    predictions: 'Predictions',
    knockout: 'Knockout',
    save: 'Save',
    matches: 'Matches',
    ranking: 'Ranking',
    participant: 'Participant',
    score: 'Score',
    rules: 'Rules',
    prizes: 'Prizes',
    noRules: 'No rules defined',
    noPrizes: 'No prizes defined',
    close: 'Close',
    public: 'Public',
    exact: 'Exact',
    outcome: 'Winner',
    goals: 'Goals',
    regulation: 'Rules',
    awards: 'Prizes',
    requests: 'Requests',
    participants: 'Participants',
    ownerMyPencas: 'My Pools',
    back: 'Back',
    next: 'Next',
    create: 'Create',
    newCompetition: 'New Competition',
    bracketPrototype: 'Bracket Prototype',
    vs: 'vs'
    adminTitle: 'Administration',
    competitions: 'Competitions',
    owners: 'Owners',
    pencas: 'Pools',
    owner: 'Owner',
    generateBracket: 'Generate/Update knockout',
    saveOrder: 'Save order',
    saveRound: 'Save round',
    groups: 'Groups',
    integrants: 'Teams',
    qualifiers: 'Qualifiers',
    group: 'Group',
    team: 'Team',
    pts: 'Pts',
    w: 'W',
    d: 'D',
    l: 'L',
    gd: 'GD',
    gf: 'GF'
  }
};

export default strings;
